"""Add Celery Job tracking fields

Revision ID: 05cf00c9d28e
Revises: 77435ab7b8fa
Create Date: 2026-02-28 20:35:40.572499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05cf00c9d28e'
down_revision: Union[str, Sequence[str], None] = '77435ab7b8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('progress', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'progress')
    # ### end Alembic commands ###
