"""Refactor Job intent to prompt

Revision ID: 31c105b97cec
Revises: faa412acce34
Create Date: 2026-03-15 14:57:25.097413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c105b97cec'
down_revision: Union[str, Sequence[str], None] = 'faa412acce34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('prompt', sa.Text(), server_default='legacy job', nullable=False))
    op.drop_column('jobs', 'intent')
    op.drop_column('jobs', 'raw_resume_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('raw_resume_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'prompt')
    # ### end Alembic commands ###
